<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"><title>Lo-Fi Python - .PEM solution</title><link href="https://lofipython.com/" rel="alternate"></link><link href="https://lofipython.com/feeds/pem-solution.tag.atom.xml" rel="self"></link><id>https://lofipython.com/</id><updated>2021-06-10T11:59:00-05:00</updated><entry><title>Python Requests SSLCertVerificationError Solution for Windows</title><link href="https://lofipython.com/how-to-fix-your-python-certificates-on-windows.html" rel="alternate"></link><published>2021-06-10T11:59:00-05:00</published><updated>2021-06-10T11:59:00-05:00</updated><author><name>pythonmarketer</name></author><id>tag:lofipython.com,2021-06-10:/how-to-fix-your-python-certificates-on-windows.html</id><summary type="html">&lt;p&gt;I initially installed my Python version from the &lt;a class="reference external" href="https://www.microsoft.com/en-us/p/python-39/9p7qfqmjrfp7"&gt;Windows Store&lt;/a&gt; and it worked fine for almost a year on my Windows 10 computer. Then I started getting this error message when trying to use the &lt;a class="reference external" href="https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification"&gt;requests library&lt;/a&gt; on all HTTP requests:&lt;/p&gt;
&lt;div class="highlight"&gt;&lt;table class="highlighttable"&gt;&lt;tr&gt;&lt;td class="linenos"&gt;&lt;div class="linenodiv"&gt;&lt;pre&gt;&lt;span class="normal"&gt;1&lt;/span&gt;&lt;/pre&gt;&lt;/div&gt;&lt;/td&gt;&lt;td class="code"&gt;&lt;div&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;span class="n"&gt;requests&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;exceptions&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;SSLError&lt;/span&gt;&lt;span class="p"&gt;:&lt;/span&gt; &lt;span class="n"&gt;HTTPSConnectionPool&lt;/span&gt;&lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="n"&gt;host&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="s1"&gt;&amp;#39;api.example.com â€¦&lt;/span&gt;&lt;/pre&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;</summary><content type="html">&lt;p&gt;I initially installed my Python version from the &lt;a class="reference external" href="https://www.microsoft.com/en-us/p/python-39/9p7qfqmjrfp7"&gt;Windows Store&lt;/a&gt; and it worked fine for almost a year on my Windows 10 computer. Then I started getting this error message when trying to use the &lt;a class="reference external" href="https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification"&gt;requests library&lt;/a&gt; on all HTTP requests:&lt;/p&gt;
&lt;div class="highlight"&gt;&lt;table class="highlighttable"&gt;&lt;tr&gt;&lt;td class="linenos"&gt;&lt;div class="linenodiv"&gt;&lt;pre&gt;&lt;span class="normal"&gt;1&lt;/span&gt;&lt;/pre&gt;&lt;/div&gt;&lt;/td&gt;&lt;td class="code"&gt;&lt;div&gt;&lt;pre&gt;&lt;span&gt;&lt;/span&gt;&lt;span class="n"&gt;requests&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;exceptions&lt;/span&gt;&lt;span class="o"&gt;.&lt;/span&gt;&lt;span class="n"&gt;SSLError&lt;/span&gt;&lt;span class="p"&gt;:&lt;/span&gt; &lt;span class="n"&gt;HTTPSConnectionPool&lt;/span&gt;&lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="n"&gt;host&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="s1"&gt;&amp;#39;api.example.com&amp;#39;&lt;/span&gt;&lt;span class="p"&gt;,&lt;/span&gt; &lt;span class="n"&gt;port&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="mi"&gt;443&lt;/span&gt;&lt;span class="p"&gt;):&lt;/span&gt; &lt;span class="n"&gt;Max&lt;/span&gt; &lt;span class="n"&gt;retries&lt;/span&gt; &lt;span class="n"&gt;exceeded&lt;/span&gt; &lt;span class="k"&gt;with&lt;/span&gt; &lt;span class="n"&gt;url&lt;/span&gt;&lt;span class="p"&gt;:&lt;/span&gt; &lt;span class="o"&gt;/&lt;/span&gt;&lt;span class="n"&gt;oauth&lt;/span&gt;&lt;span class="o"&gt;/&lt;/span&gt;&lt;span class="n"&gt;token&lt;/span&gt;&lt;span class="err"&gt;?&lt;/span&gt;&lt;span class="n"&gt;grant_type&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="n"&gt;client_credentials&lt;/span&gt; &lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="n"&gt;Caused&lt;/span&gt; &lt;span class="n"&gt;by&lt;/span&gt; &lt;span class="n"&gt;SSLError&lt;/span&gt;&lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="n"&gt;SSLCertVerificationError&lt;/span&gt;&lt;span class="p"&gt;(&lt;/span&gt;&lt;span class="mi"&gt;1&lt;/span&gt;&lt;span class="p"&gt;,&lt;/span&gt; &lt;span class="s1"&gt;&amp;#39;[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)&amp;#39;&lt;/span&gt;&lt;span class="p"&gt;)))&lt;/span&gt;
&lt;/pre&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;
&lt;p&gt;Apparently my Python certificates were not valid or up to date on my computer. These are &amp;quot;.PEM&amp;quot; or &amp;quot;.cert&amp;quot; files that certify your connection for the &lt;a class="reference external" href="https://www.ssl.com/faqs/faq-what-is-ssl/"&gt;SSL protocol&lt;/a&gt;. I googled this error until I found the &lt;a class="reference external" href="https://pypi.org/project/python-certifi-win32/"&gt;python-certifi-win32&lt;/a&gt; library. I only needed to &lt;a class="reference external" href="https://pythonmarketer.wordpress.com/2018/01/20/how-to-python-pip-install-new-libraries/"&gt;pip install&lt;/a&gt; this library and it fixed the problem:&lt;/p&gt;
&lt;dl class="docutils"&gt;
&lt;dt&gt;::&lt;/dt&gt;
&lt;dd&gt;pip install python-certifi-win32&lt;/dd&gt;
&lt;/dl&gt;
&lt;p&gt;Huge thank you to &lt;a class="reference external" href="https://pypi.org/user/andrewleech/"&gt;the maintainer&lt;/a&gt; of this package. It solved my issues and now I can make HTTP requests again!&lt;/p&gt;
</content><category term="coding, HTTP, python, Windows"></category><category term=".PEM solution"></category><category term="problem solving"></category><category term="Windows 10"></category></entry></feed>